VP-5059
VirtoCommerce/vc-github-actions pull request #31
Opened 2020-10-21 07:26 UTC by krankenbro

2020-10-22 08:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/VirtoCommerce/vc-github-actions?pullRequest=31) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/VirtoCommerce/vc-github-actions?pullRequest=31) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: krankenbro<br/>:white_check_mark: mvktsk<br/>:x: dimitri-ak<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/VirtoCommerce/vc-github-actions?pullRequest=31) it.</sub>

2020-10-22 08:53 UTC, dimitri-ak approved these changes

2020-10-23 09:53 UTC, mvktsk requested changes

2020-10-23 09:53 UTC, mvktsk commented on add-version-suffix/index.js
> +    const commitCount = await getCommitCount(branchName);
Can we add versionSuffix input parameter and use get-image-version.suffix value?

2020-10-23 09:53 UTC, mvktsk commented on build-theme/action.yml
> +   versionSuffix:
Rename `release_branch` to `releaseBranch`

2020-10-23 09:53 UTC, mvktsk commented on deploy-workflow/workflows/modules/.github/workflows/main.yml
>          uses: VirtoCommerce/vc-github-actions/publish-nuget@master
Add check `if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'}}`
In VirtoCommerce/vc-github-actions/publish-nuget remove check `if(branchName === 'dev' || branchName === 'master')`

2020-10-23 09:53 UTC, mvktsk commented on deploy-workflow/workflows/platform/.github/workflows/main.yml
>        uses: VirtoCommerce/vc-github-actions/publish-nuget@master
Add check if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'}}

2020-10-23 09:53 UTC, mvktsk commented on deploy-workflow/workflows/storefront/.github/workflows/main.yml
>          tag: ${{ steps.image.outputs.taggedVersion }}
Add parameters 
```
        imageName: "storefront"
        dockerFiles: "https://raw.githubusercontent.com/VirtoCommerce/vc-docker/master/linux/storefront/Dockerfile"
```

2020-10-23 09:53 UTC, mvktsk commented on deploy-workflow/workflows/platform/.github/workflows/main.yml
>        with:
Add parameters
```
        imageName: "platform"
        dockerFiles: "https://raw.githubusercontent.com/VirtoCommerce/vc-docker/master/linux/platform/Dockerfile;https://raw.githubusercontent.com/VirtoCommerce/vc-docker/master/linux/platform/wait-for-it.sh"
```

2020-10-23 09:53 UTC, mvktsk commented on deploy-workflow/workflows/themes/.github/workflows/main.yml
> +        tag_name: ${{ steps.image.outputs.tag }}
change `steps.image.outputs.tag` to s`teps.image.outputs.prefix`

2020-10-23 09:53 UTC, mvktsk commented on deploy-workflow/workflows/themes/.github/workflows/main.yml
> +        release_name: ${{ steps.image.outputs.tag }}
change `steps.image.outputs.tag` to s`teps.image.outputs.prefix`

2020-10-23 09:53 UTC, mvktsk commented on get-image-version/action.yml
> +  release_branch:
My mistake, please rename `release_branch` to `releaseBranch`

2020-10-23 09:53 UTC, mvktsk commented on get-image-version/index.js
> +    const releaseBranch = core.getInput("release_branch");
Rename `release_branch` to `releaseBranch`

2020-10-23 09:53 UTC, mvktsk commented on publish-blob-release/src/index.ts
> +// async function run() {
Remove commented code

2020-10-23 09:53 UTC, mvktsk commented on publish-docker-image/index.js
> +    await exec.exec (command);
Remove blank between exec and (command)

2020-10-23 09:53 UTC, mvktsk commented on publish-docker-image/index.js
> +    const dockerUser = core.getInput("docker_user").toLocaleLowerCase();
My mistake  please remove `.toLocaleLowerCase()`

2020-10-23 09:53 UTC, mvktsk commented on publish-docker-image/index.js
> +    const dockerToken = core.getInput("docker_token").toLocaleLowerCase();
My mistake, please remove `.toLocaleLowerCase()`

2020-10-23 09:53 UTC, mvktsk commented on publish-docker-image/index.js
> +    const dockerHub = core.getInput("docker_hub").toLocaleLowerCase();
My mistake, please remove `.toLocaleLowerCase()`

2020-10-23 09:53 UTC, mvktsk commented on publish-docker-image/index.js
> +    const releaseBranch = core.getInput("release_branch").toLocaleLowerCase();
My mistake, please remove `.toLocaleLowerCase()`

2020-10-23 09:53 UTC, mvktsk commented on build-theme/index.js
> +    const releaseBranch = core.getInput("release_branch");
Rename `release_branch` to `releaseBranch`

2020-10-23 09:57 UTC, mvktsk requested changes

2020-10-23 09:57 UTC, mvktsk commented on build-theme/action.yml
> +   release_branch:
Rename `release_branch` to `releaseBranch`

2020-10-26 09:58 UTC, dimitri-ak approved these changes

2020-10-26 13:13 UTC, mvktsk approved these changes

2020-10-26 13:22 UTC, merged