VP-1985: CI for modules should also publish release information to our site
VirtoCommerce/vc-github-actions pull request #56
Opened 2021-03-03 12:50 UTC by krankenbro

2021-03-04 10:10 UTC, mvktsk requested changes

2021-03-04 10:10 UTC, mvktsk commented on update-virtocommercecom/ps/utilities.ps1
> +		$contentDispositionHeaderValue = New-Object System.Net.Http.Headers.ContentDispositionHeaderValue "form-data"
Check the line spacing

2021-03-04 10:10 UTC, mvktsk commented on update-virtocommercecom/ps/utilities.ps1
> +
Check the line spacing

2021-03-15 05:38 UTC, mvktsk approved these changes

2021-03-24 13:29 UTC, krankenbro commented
Added product creation if it doesn't exist, and additional field

2021-03-25 02:56 UTC, mvktsk approved these changes

2021-03-25 13:10 UTC, merged